version: "3.8"

services:
  db:
    image: postgres:15
    container_name: exposicao-financeira-db
    restart: on-failure
    environment:
      - TZ=America/Sao_Paulo
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=s3cr3tp4ssw0rd
    ports:
      - "5432:5432"

